"""
Download EUBUCCO Sweden building data from Zenodo
Alternative method using direct file listing
"""

import os
import urllib.request
from pathlib import Path

# Create download directory
DATA_DIR = Path(__file__).parent / "data" / "eubucco"
DATA_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 70)
print("EUBUCCO Sweden Building Data - Manual Download Instructions")
print("=" * 70)
print()
print("The EUBUCCO v0.1 database is 103 GB compressed (all Europe).")
print("Individual country files are not directly accessible via API.")
print()
print("📥 DOWNLOAD OPTIONS:")
print()
print("Option 1: Official Website (RECOMMENDED)")
print("-" * 70)
print("1. Visit: https://eubucco.com/data")
print("2. Navigate the interactive map or country list")
print("3. Select 'Sweden' (SWE)")
print("4. Download the GeoPackage file")
print(f"5. Save to: {DATA_DIR}")
print()
print("Expected file: v0_1-SWE.gpkg (estimated ~500 MB - 2 GB)")
print()
print("Option 2: Zenodo Archive")
print("-" * 70)
print("1. Visit: https://zenodo.org/record/7225259")
print("2. Download: eubucco-v0_1.zip (103.3 GB - ALL countries)")
print("3. Extract only Sweden files:")
print("   - Look for files matching *SWE* pattern")
print()
print("Option 3: GitHub Repository")
print("-" * 70)
print("1. Check: https://github.com/ai4up/eubucco")
print("2. Look for data access documentation")
print("3. Follow their recommended download method")
print()
print("=" * 70)
print("EXPECTED SWEDEN DATA STRUCTURE:")
print("=" * 70)
print("v0_1-SWE.gpkg         # Main GeoPackage with building footprints")
print()
print("ATTRIBUTES:")
print("  - id              # Building ID")
print("  - geometry        # Building footprint (polygon)")
print("  - type            # Building type (residential/non-residential)")
print("  - subtype         # Detailed building subtype")  
print("  - height          # Building height (meters)")
print("  - floors          # Number of floors")
print("  - age             # Construction year")
print()
print("=" * 70)
print(f"Save location: {DATA_DIR.absolute()}")
print("=" * 70)
print()
print("After downloading, you can load the data with:")
print()
print("Python:")
print("  import geopandas as gpd")
print("  gdf = gpd.read_file('data/eubucco/v0_1-SWE.gpkg')")
print()
print("DuckDB:")
print("  SELECT * FROM ST_Read('data/eubucco/v0_1-SWE.gpkg')")
print()
