// =============================================================
// layer_docs.js — descriptive copy for every info (i) button.
//
// Kept out of viewer/index.html so the panel markup stays scannable and the
// prose is reviewable/translatable in one place. ui.js hydrates each
// <button class="info-btn" data-layer="KEY"> from this map on init.
//
// Country-specific building copy stays templated in index.html
// ({{BUILDINGS_DESC}} / {{BUILDINGS_SOURCE}}), substituted by build.py.
// =============================================================
window.LAYER_DOCS = {
  "building-layers": { title: "Building layers", desc: "The analysed building stock and optional global OSM massing for surrounding context. Use the colour-by tabs to recolour buildings by use type, energy class or construction era." },
  "selected-building": { title: "Selected building", desc: "Attribute data for the building you clicked on the map, plus the analysis tools that run against it: window-to-wall ratio, rooftop PV potential and an EnergyPlus energy simulation.", source: "EUBUCCO · Boverket EPC · PPG analysis pipeline" },
  "base-map": { title: "Base map", desc: "The map surface drawn beneath the data layers. Exactly one can be active at a time.", source: "CartoDB · Esri · Google via Cesium Ion" },
  "light-basemap": { title: "Light basemap", desc: "Neutral light street map — ideal for daytime use and coloured data overlays.", source: "CartoDB Positron · OpenStreetMap contributors" },
  "dark-basemap": { title: "Dark basemap", desc: "Dark-themed street map. Provides strong contrast for bright-coloured overlays.", source: "CartoDB Dark Matter · OpenStreetMap contributors" },
  "satellite-imagery": { title: "Satellite imagery", desc: "High-resolution aerial and satellite imagery of the viewed area and surroundings.", source: "Esri World Imagery" },
  "photorealistic-3d-tiles": { title: "Photorealistic 3D tiles", desc: "Google's photorealistic 3D tiles with detailed building textures and terrain mesh. Requires a valid Cesium Ion access token.", source: "Google via Cesium Ion" },
  "cesium-osm-buildings": { title: "Cesium OSM Buildings", desc: "Global 3D building massing from OpenStreetMap. Adds context around the analysis area, which only covers the focus district. Combine with photorealistic tiles or use on its own.", source: "Cesium OSM Buildings · OpenStreetMap contributors" },
  "traffic-layers": { title: "Traffic layers", desc: "Operational mobility layers, in two groups. Public transport (Västtrafik): live vehicle positions and stops, disruption notices, and commuter parking availability. Roads & highways (Trafikverket): roadside cameras, measured traffic flow, road-surface conditions and trunk-road rest stops. Both need the backend server running.", source: "Västtrafik open API · Trafikverket Open API" },
  "live-transit-amp-stops": { title: "Live Transit &amp; Stops", desc: "Real-time bus, tram, and ferry positions plus stop locations across Gothenburg. Requires the backend server (uvicorn) to be running.", source: "Västtrafik open API · GTFS-RT feed" },
  "traffic-disruptions": { title: "Traffic Disruptions", desc: "Live traffic disruptions, planned maintenance works, and service alerts on the public transit network. Shown as clickable markers on the map.", source: "Västtrafik Störning API" },
  "commuter-parking": { title: "Commuter Parking", desc: "Kiss-and-ride and commuter parking lots near transit stops, with live space availability where provided.", source: "Västtrafik" },
  "trafikverket-road-layers": { title: "Roads &amp; Highways (Trafikverket)", desc: "Live road-network layers from the Swedish Transport Administration covering the greater Gothenburg area: roadside cameras, measured traffic flow, road-surface conditions and rest stops. Served through the backend, which queries Trafikverket directly and caches for 60 s. Requires the backend server (uvicorn) and a TRAFIKVERKET_API_KEY in .env.", source: "Trafikverket Open API (datex II / trafikinfo v2)" },
  "traffic-cameras": { title: "Traffic Cameras", desc: "Roadside camera locations with their latest photo. Click a pin to open the image, which then refreshes every 30 seconds while the popup stays open.", source: "Trafikverket · Camera objecttype" },
  "traffic-flow": { title: "Traffic Flow", desc: "Measured vehicle flow rate and average speed at fixed detector sites. Circle size scales with flow; colour shows congestion — green under 200 veh/h, amber 200–600, red above 600. Refreshes every 5 minutes while active.", source: "Trafikverket · TrafficFlow objecttype" },
  "road-conditions": { title: "Road Conditions", desc: "Reported road-surface state (normal, slippery, ice, snow) per road section, with the affected road number and location. Green = normal, amber = caution, red = hazardous.", source: "Trafikverket · RoadCondition objecttype" },
  "road-parking": { title: "Rest Stops &amp; Parking", desc: "Trunk-road rest areas and parking facilities with opening status, operational status and capacity. Distinct from the Västtrafik commuter parking layer, which covers public-transport park-and-ride sites.", source: "Trafikverket · Parking objecttype" },
  "statistics-sweden-scb-layers": { title: "Statistics Sweden (SCB) layers", desc: "47 statistical overlays from Statistics Sweden covering population grids, administrative zones, land use areas, and the national reference grid. All loaded on demand from the SCB WFS service.", source: "Statistics Sweden (SCB) · CC0 1.0 Universal · geodata.scb.se" },
  "urban-analysis-layers": { title: "Urban Analysis layers", desc: "City-wide analytical overlays computed from OSM and EUBUCCO data. Green Index scores street segments by park proximity. Heat Island Proxy estimates thermal stress per grid cell from building energy class, age and use. Green Accessibility maps walking distance to the nearest green space.", source: "OSM · Overpass API · EUBUCCO v0.2" },
  "street-green-index": { title: "Green Index", desc: "Continuous greenness score on a 280 m grid: exp(−d/200) where d is the distance to the nearest OSM park, forest or garden. Colour runs red (no green nearby) through amber to green, with no thresholds — use it to read the gradient across a neighbourhood. Green Accessibility measures the same distance but buckets it against policy thresholds instead.", source: "OpenStreetMap green spaces (22,851 features)" },
  "urban-heat-island-proxy": { title: "Urban Heat Island Proxy", desc: "Grid-based heat island proxy (667 m cells) scored from energy class (50%), construction year (30%), and building use (20%). Green areas provide a cooling correction. Red = high thermal stress, blue = cooler areas.", source: "EUBUCCO v0.2 · Boverket EPC · OSM" },
  "green-space-accessibility": { title: "Green Space Accessibility", desc: "The same distance-to-nearest-green as Green Index, but classified against policy thresholds instead of shown as a gradient: green = within 400 m, amber = 400–800 m, red = over 800 m. The legend reports the share of the city in each band — so this answers \"how much of the city is underserved\", while Green Index answers \"how does greenness vary across this area\". Distance is centroid-to-centroid minus an equivalent-circle radius capped at 300 m.", source: "OpenStreetMap green spaces (22,851 features) · WHO green-space guidance" }
};
