import { useMemo } from "react";
import { useWizardStore } from "../store/wizard";
import { beViewerCityId } from "../config/countryNav";

// Belgian 3D viewer (Brussels, Liège) - assets/be_3d.html, generated by tools/be/build_be_viewer.py.
export default function BEMapViewer() {
  const city = useWizardStore((s) => s.project.city);
  const cityId = beViewerCityId(city);

  const viewerUrl = useMemo(() => `/be_3d.html?city=${cityId}`, [cityId]);

  return (
    <div style={{ height: "calc(100vh - 128px)", minHeight: 520 }}>
      <iframe
        key={viewerUrl}
        src={viewerUrl}
        title={`${city || "Brussels"} 3D Viewer`}
        style={{
          width: "100%",
          height: "100%",
          border: "1px solid rgba(255,255,255,0.12)",
          borderRadius: 12,
          background: "#0a0d14",
        }}
      />
    </div>
  );
}
