"""
Turn the UK and Belgium renovation-materials workbooks into the frontend's
material catalogues (frontend/src/config/materialCatalogue{UK,BE}.ts).

    python tools/catalog/ingest_material_catalogue.py

Source workbooks (compiled 2026-10-07, one sheet "All items" each):
    ../uk_cost_carbon/UK_Renovation_Materials_Catalogue.xlsx      (GBP, incl. 20% VAT)
    ../Belgium/Belgium_Renovation_Materials_Catalogue.xlsx         (EUR, incl. 21% VAT)

Edit the workbooks, not the generated .ts files. Each item keeps its price and
embodied-carbon (A1-A3) value, the quality flags, and the source text, so the UI
can say where a number came from. For insulation the thickness and thermal
conductivity (lambda) are parsed from the specification text, which is what lets
Step 4 turn "100 mm PIR" into a U-value for a given wall.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[2]
SOURCES = {
    "UK": (ROOT.parent / "uk_cost_carbon" / "UK_Renovation_Materials_Catalogue.xlsx", "GBP"),
    "BE": (ROOT.parent / "Belgium" / "Belgium_Renovation_Materials_Catalogue.xlsx", "EUR"),
}
OUT_DIR = ROOT / "frontend" / "src" / "config"

# Typical lambda (W/mK) by material when the spec gives no number - the usual
# declared values for each product family.
LAMBDA_DEFAULT = {
    "glass mineral wool": 0.037, "stone mineral wool": 0.036, "mineral wool": 0.037,
    "graphite eps": 0.032, "eps": 0.037, "xps": 0.034, "pir": 0.022, "phenolic": 0.020,
    "wood fibre": 0.040, "cellulose": 0.040, "hemp": 0.040, "sheep": 0.040, "cork": 0.040,
    "aerogel": 0.015, "vacuum": 0.007,
}


def _num(v):
    try:
        return float(v) if v not in (None, "") else None
    except (TypeError, ValueError):
        return None


def _thickness_mm(spec: str) -> float | None:
    m = re.search(r"(\d+(?:\.\d+)?)\s*mm", spec or "")
    return float(m.group(1)) if m else None


def _lambda(item: str, spec: str) -> float | None:
    vals = [float(x) for x in re.findall(r"lambda\s*~?\s*(0\.\d+)", spec or "", flags=re.I)]
    # "lambda ~0.035-0.040" -> take the range's middle
    rng = re.search(r"lambda\s*~?\s*(0\.\d+)\s*-\s*(0\.\d+)", spec or "", flags=re.I)
    if rng:
        return round((float(rng.group(1)) + float(rng.group(2))) / 2, 4)
    if vals:
        return vals[0]
    name = (item or "").lower()
    for key, lam in LAMBDA_DEFAULT.items():
        if key in name:
            return lam
    return None


def read(path: Path) -> list[dict]:
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb["All items"]
    rows = [r for r in ws.iter_rows(values_only=True) if any(c not in (None, "") for c in r)]
    head = [str(h or "").strip() for h in rows[0]]
    col = {h: i for i, h in enumerate(head)}

    def get(r, *names):
        for n in names:
            for h, i in col.items():
                if h.lower().startswith(n.lower()):
                    return r[i]
        return None

    items = []
    for r in rows[1:]:
        if not get(r, "ID"):
            continue
        item, spec, cat = str(get(r, "Item") or ""), str(get(r, "Specification") or ""), str(get(r, "Category") or "")
        is_ins = "insulation" in cat.lower()
        items.append({
            "id": str(get(r, "ID")).strip(),
            "category": cat,
            "item": item,
            "spec": spec,
            "unit": str(get(r, "Unit") or ""),
            "gwp": _num(get(r, "GWP A1")),                       # kgCO2e per unit, A1-A3
            "carbonQuality": get(r, "Carbon data quality"),
            "carbonOrigin": get(r, "Carbon data origin"),
            "biogenic": get(r, "Biogenic"),
            "priceLow": _num(get(r, "Price low")),
            "priceHigh": _num(get(r, "Price high")),
            "price": _num(get(r, "Price used incl")),            # incl. VAT, material only
            "priceQuality": get(r, "Price data quality"),
            "carbonSource": get(r, "Carbon source"),
            "priceSource": get(r, "Price source"),
            "thicknessMm": _thickness_mm(spec) if is_ins else None,
            "lambda": _lambda(item, spec) if is_ins else None,
        })
    return items


def main() -> None:
    for code, (path, cur) in SOURCES.items():
        items = read(path)
        out = OUT_DIR / f"materialCatalogue{code}.ts"
        body = json.dumps(items, ensure_ascii=False, indent=1)
        out.write_text(
            "/* GENERATED by tools/catalog/ingest_material_catalogue.py from\n"
            f" * {path.name} - edit the workbook, then re-run the script.\n"
            f" * Prices: {cur} incl. VAT, material only. Carbon: GWP A1-A3 per unit. */\n"
            'import type { CatalogueMaterial } from "./materialCatalogue";\n\n'
            f"export const CURRENCY = \"{cur}\";\n"
            f"export const MATERIALS: CatalogueMaterial[] = {body};\n",
            encoding="utf-8",
        )
        ins = [i for i in items if i["lambda"]]
        print(f"{code}: {len(items)} items ({sum(1 for i in items if i['price'])} priced, "
              f"{sum(1 for i in items if i['gwp'] is not None)} with carbon, {len(ins)} insulation with lambda) -> {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
